import { Category, PaymentMethod, MonthlyBudget, Receivable, Transaction, CardPayment, Payable } from '@/types';

export const initialCategories: Category[] = [
  { id: 'cat-1', name: 'Seguros y Servicios Fijos', icon: 'ShieldCheck', color: '#0ea5e9' },
  { id: 'cat-2', name: 'Suscripciones y Streaming', icon: 'Tv', color: '#8b5cf6' },
  { id: 'cat-3', name: 'Comida y Restaurantes', icon: 'Utensils', color: '#f59e0b' },
  { id: 'cat-4', name: 'Transporte', icon: 'Car', color: '#10b981' },
  { id: 'cat-5', name: 'Compras y Shopping', icon: 'ShoppingBag', color: '#ec4899' },
  { id: 'cat-6', name: 'Entretenimiento y Ocio', icon: 'Gamepad2', color: '#a855f7' },
  { id: 'cat-7', name: 'Viajes', icon: 'Plane', color: '#06b6d4' },
  { id: 'cat-8', name: 'Salud', icon: 'HeartPulse', color: '#ef4444' },
  { id: 'cat-9', name: 'Hogar y Electrodomesticos', icon: 'Home', color: '#14b8a6' },
  { id: 'cat-10', name: 'Tecnologia', icon: 'Laptop', color: '#6366f1' },
  { id: 'cat-11', name: 'Regalos y Terceros', icon: 'Gift', color: '#f97316' },
  { id: 'cat-12', name: 'Otros / Por Clasificar', icon: 'HelpCircle', color: '#64748b' }
];

export const initialPaymentMethods: PaymentMethod[] = [
  { id: 'pm-1', name: 'Debito', type: 'debit', color: '#10b981', icon: 'Banknote', isActive: true },
  { id: 'pm-2', name: 'TC Interbank (IBK)', type: 'credit', billingCloseDay: 26, paymentDueDay: 20, color: '#059669', icon: 'CreditCard', isActive: true, creditLimit: 5000 },
  { id: 'pm-3', name: 'TC Scotiabank', type: 'credit', billingCloseDay: 30, paymentDueDay: 23, color: '#dc2626', icon: 'CreditCard', isActive: true, creditLimit: 3000 },
  { id: 'pm-4', name: 'TC oh!', type: 'credit', billingCloseDay: 28, paymentDueDay: 25, color: '#2563eb', icon: 'CreditCard', isActive: true, creditLimit: 2500 },
  { id: 'pm-5', name: 'TC BCP', type: 'credit', billingCloseDay: 10, paymentDueDay: 7, color: '#f59e0b', icon: 'CreditCard', isActive: true, creditLimit: 4000 },
  { id: 'pm-6', name: 'Efectivo / Otro', type: 'cash', color: '#64748b', icon: 'Wallet', isActive: true }
];

export const initialSalaries = [
  { id: 'sal-1', source: 'Empleo Principal (Nómina)', amount: 2126.49, payDay: 30 }
];

export const initialMonthlyBudgets: Record<string, MonthlyBudget> = {
  '2026-08': {
    year: 2026,
    month: 8,
    baseSalary: 2126.49,
    salaries: initialSalaries,
    initialDebitBalance: 2044.67,
    otherIncomes: []
  },
  '2026-09': {
    year: 2026,
    month: 9,
    baseSalary: 2126.49,
    salaries: initialSalaries,
    initialDebitBalance: 3904.66,
    otherIncomes: [
      { id: 'oi-1', description: 'Disney', amount: 103.50, receivedDate: '2026-09-05' }
    ]
  },
  '2026-10': {
    year: 2026,
    month: 10,
    baseSalary: 2126.49,
    salaries: initialSalaries,
    initialDebitBalance: 1994.46,
    otherIncomes: []
  },
  '2026-11': {
    year: 2026,
    month: 11,
    baseSalary: 2126.49,
    salaries: initialSalaries,
    initialDebitBalance: 2308.74,
    otherIncomes: []
  },
  '2026-12': {
    year: 2026,
    month: 12,
    baseSalary: 2126.49,
    salaries: initialSalaries,
    initialDebitBalance: 4141.37,
    otherIncomes: []
  }
};

export const initialReceivables: Receivable[] = [
  { id: 'rec-1', debtorName: 'Mamá', description: 'Préstamo personal', originalAmount: 140.00, paidAmount: 0, remainingAmount: 140.00, status: 'pending', createdAt: '2026-09-01' },
  { id: 'rec-2', debtorName: 'Papá', description: 'Préstamo personal', originalAmount: 140.00, paidAmount: 0, remainingAmount: 140.00, status: 'pending', createdAt: '2026-09-01' },
  { id: 'rec-3', debtorName: 'Mamá', description: 'Detalle pendiente', originalAmount: 126.56, paidAmount: 0, remainingAmount: 126.56, status: 'pending', createdAt: '2026-09-05' }
];

export const initialPayables: Payable[] = [
  {
    id: 'pay-1',
    creditorName: 'Carlos R.',
    description: 'Préstamo para laptop',
    totalAmount: 1200.00,
    originalAmount: 1200.00,
    paidAmount: 400.00,
    remainingAmount: 800.00,
    issueDate: '2026-08-15',
    dueDate: '2026-11-15',
    isCreditedToDebit: false,
    status: 'PARTIALLY_PAID',
    notes: 'Préstamo personal a devolver en cuotas',
    payments: [
      {
        id: 'pp-1',
        payableId: 'pay-1',
        amountPaid: 400.00,
        amount: 400.00,
        paymentDate: '2026-09-05',
        paymentMethodId: 'pm-1',
        notes: 'Primera cuota pagada por transferencia'
      }
    ]
  }
];

export const initialCardPayments: CardPayment[] = [
  { id: 'cp-1', paymentMethodId: 'pm-2', amountPaid: 80.95, paymentDate: '2026-08-20' },
  { id: 'cp-2', paymentMethodId: 'pm-2', amountPaid: 2435.29, paymentDate: '2026-09-20' },
  { id: 'cp-3', paymentMethodId: 'pm-4', amountPaid: 505.98, paymentDate: '2026-09-25' }
];

export const initialTransactions: Transaction[] = [
  {
    "id": "tx-1",
    "date": "2026-08-09",
    "description": "Spotify",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 32.9,
    "exchangeRate": 1.0,
    "amountPen": 32.9,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-2",
    "date": "2026-08-03",
    "description": "Disney+",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 68.9,
    "exchangeRate": 1.0,
    "amountPen": 68.9,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-3",
    "date": "2026-08-18",
    "description": "Crunchyroll",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 23.9,
    "exchangeRate": 1.0,
    "amountPen": 23.9,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-4",
    "date": "2026-08-26",
    "description": "iCloud",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 42.9,
    "exchangeRate": 1.0,
    "amountPen": 42.9,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-5",
    "date": "2026-08-16",
    "description": "Paramount+",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 21.5,
    "exchangeRate": 1.0,
    "amountPen": 21.5,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-6",
    "date": "2026-08-01",
    "description": "Seguro de TC",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 10.76,
    "exchangeRate": 1.0,
    "amountPen": 10.76,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-7",
    "date": "2026-08-31",
    "description": "Celular",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 80.0,
    "exchangeRate": 1.0,
    "amountPen": 80.0,
    "paymentDueDate": "2026-08-31",
    "isFixedSubscription": true
  },
  {
    "id": "tx-8",
    "date": "2026-08-31",
    "description": "Seguro oncologico",
    "categoryId": "cat-8",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 13.0,
    "exchangeRate": 1.0,
    "amountPen": 13.0,
    "paymentDueDate": "2026-08-31",
    "isFixedSubscription": true
  },
  {
    "id": "tx-9",
    "date": "2026-07-27",
    "description": "Tambo",
    "categoryId": "cat-3",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 62.29,
    "exchangeRate": 1.0,
    "amountPen": 62.29,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-10",
    "date": "2026-07-27",
    "description": "Cocos",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 35.0,
    "exchangeRate": 1.0,
    "amountPen": 35.0,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-11",
    "date": "2026-07-27",
    "description": "Cocos",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 220.0,
    "exchangeRate": 1.0,
    "amountPen": 220.0,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-12",
    "date": "2026-07-27",
    "description": "Javier Restaurant",
    "categoryId": "cat-3",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 169.0,
    "exchangeRate": 1.0,
    "amountPen": 169.0,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-13",
    "date": "2026-07-27",
    "description": "Miniso",
    "categoryId": "cat-11",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 44.9,
    "exchangeRate": 1.0,
    "amountPen": 44.9,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-14",
    "date": "2026-07-29",
    "description": "Cinemark",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 39.2,
    "exchangeRate": 1.0,
    "amountPen": 39.2,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-15",
    "date": "2026-07-29",
    "description": "McDonald's",
    "categoryId": "cat-3",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 20.9,
    "exchangeRate": 1.0,
    "amountPen": 20.9,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-16",
    "date": "2026-07-30",
    "description": "Claude",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "USD",
    "originalAmount": 23.6,
    "exchangeRate": 3.43,
    "amountPen": 80.94800000000001,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-17",
    "date": "2025-08-01",
    "description": "Casaca Cuota 2",
    "categoryId": "cat-11",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 131.68,
    "exchangeRate": 1.0,
    "amountPen": 131.68,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-18",
    "date": "2026-08-01",
    "description": "FireStick",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 209.0,
    "exchangeRate": 1.0,
    "amountPen": 209.0,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-19",
    "date": "2026-08-01",
    "description": "Hervidora",
    "categoryId": "cat-11",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 258.9,
    "exchangeRate": 1.0,
    "amountPen": 258.9,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-20",
    "date": "2026-08-02",
    "description": "Taladro",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 429.9,
    "exchangeRate": 1.0,
    "amountPen": 429.9,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-21",
    "date": "2026-08-02",
    "description": "Pedidos Ya",
    "categoryId": "cat-3",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 42.9,
    "exchangeRate": 1.0,
    "amountPen": 42.9,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-22",
    "date": "2026-08-02",
    "description": "Sodimac",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 32.8,
    "exchangeRate": 1.0,
    "amountPen": 32.8,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-23",
    "date": "2026-08-05",
    "description": "Shalom",
    "categoryId": "cat-11",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 26.0,
    "exchangeRate": 1.0,
    "amountPen": 26.0,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-24",
    "date": "2026-08-06",
    "description": "Temu",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 123.03,
    "exchangeRate": 1.0,
    "amountPen": 123.03,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-25",
    "date": "2026-08-03",
    "description": "AliExpress",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 334.95,
    "exchangeRate": 1.0,
    "amountPen": 334.95,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-26",
    "date": "2026-08-16",
    "description": "Didi",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 16.1,
    "exchangeRate": 1.0,
    "amountPen": 16.1,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-27",
    "date": "2026-08-19",
    "description": "Otto Grill",
    "categoryId": "cat-3",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 27.8,
    "exchangeRate": 1.0,
    "amountPen": 27.8,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-28",
    "date": "2026-08-09",
    "description": "Popeyes",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-3",
    "currency": "PEN",
    "originalAmount": 40.0,
    "exchangeRate": 1.0,
    "amountPen": 40.0,
    "paymentDueDate": "2026-09-23",
    "isFixedSubscription": false
  },
  {
    "id": "tx-29",
    "date": "2026-07-26",
    "description": "Uber",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 10.4,
    "exchangeRate": 1.0,
    "amountPen": 10.4,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-30",
    "date": "2026-07-29",
    "description": "Uber",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 5.0,
    "exchangeRate": 1.0,
    "amountPen": 5.0,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-31",
    "date": "2026-07-29",
    "description": "Temu",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 161.02,
    "exchangeRate": 1.0,
    "amountPen": 161.02,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-32",
    "date": "2026-08-05",
    "description": "Temu",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 2.55,
    "exchangeRate": 1.0,
    "amountPen": 2.55,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-33",
    "date": "2026-08-08",
    "description": "Dubai",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 93.0,
    "exchangeRate": 1.0,
    "amountPen": 93.0,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-34",
    "date": "2026-08-08",
    "description": "Uber",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 19.5,
    "exchangeRate": 1.0,
    "amountPen": 19.5,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-35",
    "date": "2026-08-09",
    "description": "Uber",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 27.9,
    "exchangeRate": 1.0,
    "amountPen": 27.9,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-36",
    "date": "2026-08-09",
    "description": "Sr Feudal",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 127.9,
    "exchangeRate": 1.0,
    "amountPen": 127.9,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-37",
    "date": "2026-08-15",
    "description": "Uber",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 18.1,
    "exchangeRate": 1.0,
    "amountPen": 18.1,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-38",
    "date": "2026-08-15",
    "description": "Mifarma",
    "categoryId": "cat-8",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 18.9,
    "exchangeRate": 1.0,
    "amountPen": 18.9,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-39",
    "date": "2026-08-19",
    "description": "Uber",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 9.1,
    "exchangeRate": 1.0,
    "amountPen": 9.1,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-40",
    "date": "2026-08-12",
    "description": "Mercado Libre",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 267.92,
    "exchangeRate": 1.0,
    "amountPen": 267.92,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-41",
    "date": "2026-08-15",
    "description": "Tambo",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 22.38,
    "exchangeRate": 1.0,
    "amountPen": 22.38,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-42",
    "date": "2026-09-10",
    "description": "Escritorio",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 450.0,
    "exchangeRate": 1.0,
    "amountPen": 450.0,
    "paymentDueDate": "2026-09-10",
    "isFixedSubscription": false
  },
  {
    "id": "tx-43",
    "date": "2026-09-10",
    "description": "Pasajes",
    "categoryId": "cat-7",
    "paymentMethodId": "pm-1",
    "currency": "USD",
    "originalAmount": 109.0,
    "exchangeRate": 3.43,
    "amountPen": 373.87,
    "paymentDueDate": "2026-09-10",
    "isFixedSubscription": false
  },
  {
    "id": "tx-44",
    "date": "2026-08-22",
    "description": "Cineplanet",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 79.0,
    "exchangeRate": 1.0,
    "amountPen": 79.0,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-45",
    "date": "2026-08-22",
    "description": "Cineplanet",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 70.0,
    "exchangeRate": 1.0,
    "amountPen": 70.0,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-46",
    "date": "2026-08-23",
    "description": "Sarcletti",
    "categoryId": "cat-3",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 50.0,
    "exchangeRate": 1.0,
    "amountPen": 50.0,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-47",
    "date": "2026-08-23",
    "description": "Cineplanet",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 50.0,
    "exchangeRate": 1.0,
    "amountPen": 50.0,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-48",
    "date": "2026-08-27",
    "description": "Integraci\u00f3n BCP",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 45.0,
    "exchangeRate": 1.0,
    "amountPen": 45.0,
    "paymentDueDate": "2026-08-27",
    "isFixedSubscription": false
  },
  {
    "id": "tx-49",
    "date": "2026-08-28",
    "description": "Steam",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 15.0,
    "exchangeRate": 1.0,
    "amountPen": 15.0,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-50",
    "date": "2026-08-28",
    "description": "Steam",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 15.0,
    "exchangeRate": 1.0,
    "amountPen": 15.0,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-51",
    "date": "2026-08-26",
    "description": "Desgravamen",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 10.08,
    "exchangeRate": 1.0,
    "amountPen": 10.08,
    "paymentDueDate": "2026-09-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-52",
    "date": "2026-08-28",
    "description": "Didi",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 19.1,
    "exchangeRate": 1.0,
    "amountPen": 19.1,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-53",
    "date": "2026-08-29",
    "description": "Didi",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 7.5,
    "exchangeRate": 1.0,
    "amountPen": 7.5,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-54",
    "date": "2026-08-30",
    "description": "Zapravka",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 20.0,
    "exchangeRate": 1.0,
    "amountPen": 20.0,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-55",
    "date": "2026-08-30",
    "description": "Claude",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "USD",
    "originalAmount": 23.6,
    "exchangeRate": 3.43,
    "amountPen": 80.94800000000001,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-56",
    "date": "2026-08-30",
    "description": "Cineplanet",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 10.0,
    "exchangeRate": 1.0,
    "amountPen": 10.0,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-57",
    "date": "2026-08-30",
    "description": "Taxi",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 12.5,
    "exchangeRate": 1.0,
    "amountPen": 12.5,
    "paymentDueDate": "2026-08-30",
    "isFixedSubscription": false
  },
  {
    "id": "tx-58",
    "date": "2026-08-30",
    "description": "Cigarros",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 8.0,
    "exchangeRate": 1.0,
    "amountPen": 8.0,
    "paymentDueDate": "2026-08-30",
    "isFixedSubscription": false
  },
  {
    "id": "tx-59",
    "date": "2026-08-30",
    "description": "Cigarros",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 8.0,
    "exchangeRate": 1.0,
    "amountPen": 8.0,
    "paymentDueDate": "2026-08-30",
    "isFixedSubscription": false
  },
  {
    "id": "tx-60",
    "date": "2026-08-30",
    "description": "Trago Zapravka",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 100.0,
    "exchangeRate": 1.0,
    "amountPen": 100.0,
    "paymentDueDate": "2026-08-30",
    "isFixedSubscription": false
  },
  {
    "id": "tx-61",
    "date": "2026-08-29",
    "description": "Uber",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 7.1,
    "exchangeRate": 1.0,
    "amountPen": 7.1,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-62",
    "date": "2026-08-30",
    "description": "Uber",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 28.3,
    "exchangeRate": 1.0,
    "amountPen": 28.3,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-63",
    "date": "2026-08-26",
    "description": "Desgravamen",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 12.61,
    "exchangeRate": 1.0,
    "amountPen": 12.61,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-64",
    "date": "2026-08-28",
    "description": "Pedidos Ya",
    "categoryId": "cat-3",
    "paymentMethodId": "pm-4",
    "currency": "PEN",
    "originalAmount": 55.2,
    "exchangeRate": 1.0,
    "amountPen": 55.2,
    "paymentDueDate": "2026-09-25",
    "isFixedSubscription": false
  },
  {
    "id": "tx-65",
    "date": "2026-08-31",
    "description": "TRC",
    "categoryId": "cat-7",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 210.0,
    "exchangeRate": 1.0,
    "amountPen": 210.0,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-66",
    "date": "2026-08-31",
    "description": "TRC",
    "categoryId": "cat-7",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 70.0,
    "exchangeRate": 1.0,
    "amountPen": 70.0,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-67",
    "date": "2026-09-09",
    "description": "Spotify",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 32.9,
    "exchangeRate": 1.0,
    "amountPen": 32.9,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-68",
    "date": "2026-09-03",
    "description": "Disney+",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 68.9,
    "exchangeRate": 1.0,
    "amountPen": 68.9,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-69",
    "date": "2026-09-18",
    "description": "Crunchyroll",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 23.9,
    "exchangeRate": 1.0,
    "amountPen": 23.9,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-70",
    "date": "2026-09-26",
    "description": "iCloud",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 42.9,
    "exchangeRate": 1.0,
    "amountPen": 42.9,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-71",
    "date": "2026-09-16",
    "description": "Paramount+",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 21.5,
    "exchangeRate": 1.0,
    "amountPen": 21.5,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-72",
    "date": "2026-09-01",
    "description": "Seguro de TC",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 10.76,
    "exchangeRate": 1.0,
    "amountPen": 10.76,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-73",
    "date": "2026-09-30",
    "description": "Celular",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 80.0,
    "exchangeRate": 1.0,
    "amountPen": 80.0,
    "paymentDueDate": "2026-09-30",
    "isFixedSubscription": true
  },
  {
    "id": "tx-74",
    "date": "2026-09-30",
    "description": "Seguro oncologico",
    "categoryId": "cat-8",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 13.0,
    "exchangeRate": 1.0,
    "amountPen": 13.0,
    "paymentDueDate": "2026-09-30",
    "isFixedSubscription": true
  },
  {
    "id": "tx-75",
    "date": "2026-09-01",
    "description": "Playstation",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-5",
    "currency": "USD",
    "originalAmount": 8.84,
    "exchangeRate": 3.43,
    "amountPen": 30.3212,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-76",
    "date": "2026-09-01",
    "description": "Victorinox",
    "categoryId": "cat-11",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 269.1,
    "exchangeRate": 1.0,
    "amountPen": 269.1,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-77",
    "date": "2026-09-01",
    "description": "Cineplanet",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 20.0,
    "exchangeRate": 1.0,
    "amountPen": 20.0,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-78",
    "date": "2026-09-25",
    "description": "Casaca 3",
    "categoryId": "cat-11",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 131.68,
    "exchangeRate": 1.0,
    "amountPen": 131.68,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-79",
    "date": "2026-09-02",
    "description": "Cineplanet",
    "categoryId": "cat-6",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 28.5,
    "exchangeRate": 1.0,
    "amountPen": 28.5,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-80",
    "date": "2026-09-04",
    "description": "McDonalds",
    "categoryId": "cat-3",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 26.9,
    "exchangeRate": 1.0,
    "amountPen": 26.9,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-81",
    "date": "2026-09-05",
    "description": "Farmacia",
    "categoryId": "cat-5",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 14.5,
    "exchangeRate": 1.0,
    "amountPen": 14.5,
    "paymentDueDate": "2026-10-20",
    "isFixedSubscription": false
  },
  {
    "id": "tx-82",
    "date": "2026-09-04",
    "description": "Taxi Trux",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 8.0,
    "exchangeRate": 1.0,
    "amountPen": 8.0,
    "paymentDueDate": "2026-09-04",
    "isFixedSubscription": false
  },
  {
    "id": "tx-83",
    "date": "2026-09-04",
    "description": "Taxi Trux",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 9.0,
    "exchangeRate": 1.0,
    "amountPen": 9.0,
    "paymentDueDate": "2026-09-04",
    "isFixedSubscription": false
  },
  {
    "id": "tx-84",
    "date": "2026-09-05",
    "description": "Taxi Trux",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 12.0,
    "exchangeRate": 1.0,
    "amountPen": 12.0,
    "paymentDueDate": "2026-09-05",
    "isFixedSubscription": false
  },
  {
    "id": "tx-85",
    "date": "2026-09-05",
    "description": "Taxi Trux",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 14.0,
    "exchangeRate": 1.0,
    "amountPen": 14.0,
    "paymentDueDate": "2026-09-05",
    "isFixedSubscription": false
  },
  {
    "id": "tx-86",
    "date": "2026-09-06",
    "description": "Taxi Trux",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 11.0,
    "exchangeRate": 1.0,
    "amountPen": 11.0,
    "paymentDueDate": "2026-09-06",
    "isFixedSubscription": false
  },
  {
    "id": "tx-87",
    "date": "2026-09-06",
    "description": "Taxi Trux",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 13.0,
    "exchangeRate": 1.0,
    "amountPen": 13.0,
    "paymentDueDate": "2026-09-06",
    "isFixedSubscription": false
  },
  {
    "id": "tx-88",
    "date": "2026-09-07",
    "description": "Taxi Trux",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 8.9,
    "exchangeRate": 1.0,
    "amountPen": 8.9,
    "paymentDueDate": "2026-09-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-89",
    "date": "2026-09-07",
    "description": "Uber",
    "categoryId": "cat-4",
    "paymentMethodId": "pm-5",
    "currency": "PEN",
    "originalAmount": 5.1,
    "exchangeRate": 1.0,
    "amountPen": 5.1,
    "paymentDueDate": "2026-10-07",
    "isFixedSubscription": false
  },
  {
    "id": "tx-90",
    "date": "2026-10-01",
    "description": "Seguro de TC",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 10.76,
    "exchangeRate": 1.0,
    "amountPen": 10.76,
    "paymentDueDate": "2026-11-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-91",
    "date": "2026-10-03",
    "description": "Disney+",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 68.9,
    "exchangeRate": 1.0,
    "amountPen": 68.9,
    "paymentDueDate": "2026-11-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-92",
    "date": "2026-10-09",
    "description": "Spotify",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 32.9,
    "exchangeRate": 1.0,
    "amountPen": 32.9,
    "paymentDueDate": "2026-11-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-93",
    "date": "2026-10-16",
    "description": "Paramount+",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 21.5,
    "exchangeRate": 1.0,
    "amountPen": 21.5,
    "paymentDueDate": "2026-11-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-94",
    "date": "2026-10-18",
    "description": "Crunchyroll",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 23.9,
    "exchangeRate": 1.0,
    "amountPen": 23.9,
    "paymentDueDate": "2026-11-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-95",
    "date": "2026-10-26",
    "description": "iCloud",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 42.9,
    "exchangeRate": 1.0,
    "amountPen": 42.9,
    "paymentDueDate": "2026-11-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-96",
    "date": "2026-10-30",
    "description": "Celular",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 80.0,
    "exchangeRate": 1.0,
    "amountPen": 80.0,
    "paymentDueDate": "2026-10-30",
    "isFixedSubscription": true
  },
  {
    "id": "tx-97",
    "date": "2026-10-30",
    "description": "Seguro oncologico",
    "categoryId": "cat-8",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 13.0,
    "exchangeRate": 1.0,
    "amountPen": 13.0,
    "paymentDueDate": "2026-10-30",
    "isFixedSubscription": true
  },
  {
    "id": "tx-98",
    "date": "2026-11-01",
    "description": "Seguro de TC",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 10.76,
    "exchangeRate": 1.0,
    "amountPen": 10.76,
    "paymentDueDate": "2026-12-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-99",
    "date": "2026-11-03",
    "description": "Disney+",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 68.9,
    "exchangeRate": 1.0,
    "amountPen": 68.9,
    "paymentDueDate": "2026-12-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-100",
    "date": "2026-11-09",
    "description": "Spotify",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 32.9,
    "exchangeRate": 1.0,
    "amountPen": 32.9,
    "paymentDueDate": "2026-12-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-101",
    "date": "2026-11-16",
    "description": "Paramount+",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 21.5,
    "exchangeRate": 1.0,
    "amountPen": 21.5,
    "paymentDueDate": "2026-12-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-102",
    "date": "2026-11-18",
    "description": "Crunchyroll",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 23.9,
    "exchangeRate": 1.0,
    "amountPen": 23.9,
    "paymentDueDate": "2026-12-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-103",
    "date": "2026-11-26",
    "description": "iCloud",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 42.9,
    "exchangeRate": 1.0,
    "amountPen": 42.9,
    "paymentDueDate": "2026-12-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-104",
    "date": "2026-11-30",
    "description": "Celular",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 80.0,
    "exchangeRate": 1.0,
    "amountPen": 80.0,
    "paymentDueDate": "2026-11-30",
    "isFixedSubscription": true
  },
  {
    "id": "tx-105",
    "date": "2026-11-30",
    "description": "Seguro oncologico",
    "categoryId": "cat-8",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 13.0,
    "exchangeRate": 1.0,
    "amountPen": 13.0,
    "paymentDueDate": "2026-11-30",
    "isFixedSubscription": true
  },
  {
    "id": "tx-106",
    "date": "2026-12-01",
    "description": "Seguro de TC",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 10.76,
    "exchangeRate": 1.0,
    "amountPen": 10.76,
    "paymentDueDate": "2027-01-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-107",
    "date": "2026-12-03",
    "description": "Disney+",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 68.9,
    "exchangeRate": 1.0,
    "amountPen": 68.9,
    "paymentDueDate": "2027-01-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-108",
    "date": "2026-12-09",
    "description": "Spotify",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 32.9,
    "exchangeRate": 1.0,
    "amountPen": 32.9,
    "paymentDueDate": "2027-01-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-109",
    "date": "2026-12-16",
    "description": "Paramount+",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 21.5,
    "exchangeRate": 1.0,
    "amountPen": 21.5,
    "paymentDueDate": "2027-01-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-110",
    "date": "2026-12-18",
    "description": "Crunchyroll",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 23.9,
    "exchangeRate": 1.0,
    "amountPen": 23.9,
    "paymentDueDate": "2027-01-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-111",
    "date": "2026-12-26",
    "description": "iCloud",
    "categoryId": "cat-2",
    "paymentMethodId": "pm-2",
    "currency": "PEN",
    "originalAmount": 42.9,
    "exchangeRate": 1.0,
    "amountPen": 42.9,
    "paymentDueDate": "2027-01-20",
    "isFixedSubscription": true
  },
  {
    "id": "tx-112",
    "date": "2026-12-30",
    "description": "Celular",
    "categoryId": "cat-1",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 80.0,
    "exchangeRate": 1.0,
    "amountPen": 80.0,
    "paymentDueDate": "2026-12-31",
    "isFixedSubscription": true
  },
  {
    "id": "tx-113",
    "date": "2026-12-30",
    "description": "Seguro oncologico",
    "categoryId": "cat-8",
    "paymentMethodId": "pm-1",
    "currency": "PEN",
    "originalAmount": 13.0,
    "exchangeRate": 1.0,
    "amountPen": 13.0,
    "paymentDueDate": "2026-12-31",
    "isFixedSubscription": true
  }
];
